#!/usr/bin/env bash

# Ray tracer environment variables
export RAYTRACER_HOME=`pwd`

export RAYTRACER_SCENES=$RAYTRACER_HOME/scenes
export RAYTRACER_SDP_SCENES=$RAYTRACER_HOME/scenes/spd3_14

# Set up path
export PATH=`pwd`/tools:$PATH
